// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TestApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221130081757_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TaskBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("task_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("task_type").HasValue("TaskBase");
                });

            modelBuilder.Entity("TaskA", b =>
                {
                    b.HasBaseType("TaskBase");

                    b.Property<int>("RandomProp")
                        .HasColumnType("int")
                        .HasColumnName("TaskA_RandomProp");

                    b.Property<int>("TaskAProp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("a");
                });

            modelBuilder.Entity("TaskB", b =>
                {
                    b.HasBaseType("TaskBase");

                    b.Property<int>("RandomProp")
                        .HasColumnType("int");

                    b.Property<int>("TaskBProp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("b");
                });
#pragma warning restore 612, 618
        }
    }
}
